In [3]:
import pandas as pd

df = pd.read_csv("./vgsales.csv")

In [4]:
df.head()

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         64016 non-null  object
 1   console       64016 non-null  object
 2   genre         64016 non-null  object
 3   publisher     64016 non-null  object
 4   developer     63999 non-null  object
 5   critic_score  6678 non-null   float64
 6   total_sales   18922 non-null  float64
 7   na_sales      12637 non-null  float64
 8   jp_sales      6726 non-null   float64
 9   pal_sales     12824 non-null  float64
 10  other_sales   15128 non-null  float64
 11  release_date  56965 non-null  object
dtypes: float64(6), object(6)
memory usage: 5.9+ MB

In [17]:
#3. 장르별 세계 판매량 합계를 출력한다.
grouped = df.groupby("genre")
sum_grouped = grouped['total_sales'].sum().sort_values(ascending=False)
sum_grouped

genre
Sports              1187.51
Action              1125.89
Shooter              995.50
Misc                 557.79
Racing               525.75
Role-Playing         426.80
Platform             349.15
Fighting             341.13
Adventure            325.39
Simulation           300.65
Action-Adventure     148.52
Puzzle               127.28
Strategy             118.31
Music                 51.75
MMO                    9.31
Party                  6.21
Visual Novel           5.78
Sandbox                1.89
Education              0.97
Board Game             0.33
Name: total_sales, dtype: float64

In [25]:
# 4. 플랫폼별 세계 판매량 평균을 출력한다.
grouped = df.groupby("console")
mean_grouped = grouped['total_sales'].mean().sort_values(ascending=False)
mean_grouped

console
GBC     1.446667
NES     0.998542
GEN     0.697407
X360    0.660361
PS3     0.622923
          ...
WinP         NaN
XS           NaN
ZXS          NaN
iOS          NaN
iQue         NaN
Name: total_sales, Length: 81, dtype: float64

In [24]:
# 5. 개발사별 게임 출시 개수를 출력한다.
grouped = df.groupby("developer")
count_grouped = grouped['title'].count().sort_values(ascending=False)
count_grouped

developer
Unknown              4435
Konami                976
Sega                  915
Capcom                870
Namco                 489
                     ...
Kaare Kjellerup         1
KSYM                    1
KRITZELKRATZ 3000       1
KRG Soft                1
zio3                    1
Name: title, Length: 8862, dtype: int64

In [27]:
# 6. 플랫폼별 세계 판매량, 북미 판매량, 일본 판매량, 유럽 및 지역 아프리카 판매량, 기타 지역 판매량의 합계와 평균을 출력한다.

grouped = df.groupby("console")[["total_sales","na_sales","jp_sales","pal_sales","other_sales"]].agg(["sum", "mean"]).sort_values(by=("jp_sales", "sum"), ascending=False)
grouped

        total_sales           na_sales           jp_sales           pal_sales  \
                sum      mean      sum      mean      sum      mean       sum
console
PS           546.25  0.483407   263.26  0.283380    88.32  0.250198    163.73
PS2         1027.76  0.483424   489.96  0.311878    87.63  0.112780    296.37
PS3          839.70  0.622923   351.10  0.363082    67.68  0.095324    302.22
DS           458.17  0.191223   264.84  0.176325    64.20  0.076520     94.33
SNES          65.71  0.333553     6.84  0.570000    57.14  0.296062      1.46
...             ...       ...      ...       ...      ...       ...       ...
MS             0.00       NaN     0.00       NaN     0.00       NaN      0.00
MSD            0.00       NaN     0.00       NaN     0.00       NaN      0.00
MSX            0.00       NaN     0.00       NaN     0.00       NaN      0.00
NGage          0.00       NaN     0.00       NaN     0.00       NaN      0.00
iQue           0.00       NaN     0.00       NaN     0.00       NaN      0.00

                  other_sales
             mean         sum      mean
console
PS       0.176243       31.10  0.027669
PS2      0.186279      153.94  0.096879
PS3      0.307760      118.93  0.108910
DS       0.076195       33.88  0.019906
SNES     0.132727        0.26  0.002680
...           ...         ...       ...
MS            NaN        0.00       NaN
MSD           NaN        0.00       NaN
MSX           NaN        0.00       NaN
NGage         NaN        0.00       NaN
iQue          NaN        0.00       NaN

[81 rows x 10 columns]

In [16]:
# 7. 평론가 점수의 평균이 9.5가 넘는 게임 개발사를 선택해서 출력한다.
grouped = df.groupby("developer")

# mean_grouped = grouped['critic_score'].mean()
# mean_grouped = mean_grouped[mean_grouped > 9.5]
# mean_grouped


def greater_score(group):
    return group['critic_score'].mean() > 9.5

grouped.filter(greater_score)

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
7,Red Dead Redemption 2,PS4,Action-Adventure,Rockstar Games,Rockstar Games,9.8,13.94,5.26,0.21,6.21,2.26,2018-10-26
59,Red Dead Redemption 2,XOne,Action-Adventure,Rockstar Games,Rockstar Games,NaN,5.77,3.76,NaN,1.47,0.54,2018-10-26
285,BioShock,X360,Shooter,2K Games,2K Australia / 2K Boston,9.6,2.83,1.65,0.05,0.85,0.28,2007-08-21
18922,God of War,Series,Action,Sony Interactive Entertainment,SIE Santa Monica Studio,NaN,NaN,NaN,NaN,NaN,NaN,2005-03-22
18925,God of War (2018),All,Action,Sony Interactive Entertainment,SIE Santa Monica Studio,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-20
18927,God of War (2018),PS4,Action,Sony Interactive Entertainment,SIE Santa Monica Studio,9.7,NaN,NaN,NaN,NaN,NaN,2018-04-20
20878,Grand Theft Auto Compilation,PS,Action,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,2002-01-01
24681,The Legend of Zelda: A Link to the Past,GBA,Adventure,Nintendo,"Flagship Co., Ltd. / Nintendo EAD",9.6,NaN,NaN,NaN,NaN,NaN,2002-12-03
29008,Minecraft,All,Action-Adventure,Mojang,Mojang AB,NaN,NaN,NaN,NaN,NaN,NaN,2011-11-18
29216,God of War,PC,Action-Adventure,PlayStation PC,SIE Santa Monica Studio,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14
29894,Grand Theft Auto V,PS5,Action-Adventure,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-01
29895,Grand Theft Auto V,XS,Action-Adventure,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-01
29896,Grand Theft Auto VI,All,Action-Adventure,Unknown,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29897,Grand Theft Auto VI,PS5,Action-Adventure,Unknown,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29898,Grand Theft Auto VI,XS,Action-Adventure,Unknown,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30074,Minecraft: Dungeons,NS,Action-Adventure,Microsoft Game Studios,Mojang AB,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-26
30075,Minecraft: Dungeons,PS4,Action-Adventure,Microsoft Game Studios,Mojang AB,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-26
30184,Red Dead Redemption 2,PC,Action-Adventure,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-05
31619,The gamrReview Test Game,NES,Fighting,Unknown,VGChartz,10.0,NaN,NaN,NaN,NaN,NaN,1994-01-13
32178,Minecraft,PC,Misc,Mojang,Mojang AB,10.0,NaN,NaN,NaN,NaN,NaN,2010-05-10
52127,BioShock,PC,Shooter,2K Games,2K Australia / 2K Boston,9.6,NaN,NaN,NaN,NaN,NaN,2007-08-21
52632,BioShock,XBL,Shooter,2K Games,2K Australia / 2K Boston,9.6,NaN,NaN,NaN,NaN,NaN,2009-08-06
53223,Fusion: Genesis,XBL,Shooter,Microsoft,Starfire Studios,10.0,NaN,NaN,NaN,NaN,NaN,2011-11-09